<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AiCodeHarness.Application/AiCodeHarness.Application.csproj" />
    <ProjectReference Include="../AiCodeHarness.Domain/AiCodeHarness.Domain.csproj" />
    <ProjectReference Include="../AiCodeHarness.Infrastructure/AiCodeHarness.Infrastructure.csproj" />
  </ItemGroup>
</Project>
